### ISSUE TITLE
Co-maintainer

### ISSUE THREAD

**Issue by manuelm** [niczero/minion-backend-storable#11]
Hi Nic,

we are still using the minon storable backend and I'm publishing compatibility updates in my private repo. Since you didn't accept my PR I'm asking if you could add me as a co-maintainer in PAUSE (https://pause.perl.org/pause/query?ACTION=pause_04about#add-comaintainer) so I can (hopefully) publish new versions myself. My pause account is "manuelm". Thank you.

**Comment by niczero** [comment]
No PR referenced.
