### ISSUE TITLE
Not working with Minion 6.0+

### ISSUE THREAD

**Issue by iynehz** [niczero/minion-backend-storable#3]
With Minion 6.03 I get this error 
```
Method "receive" not implemented by subclass
```

Also see https://metacpan.org/source/SRI/Minion-6.03/Changes#L19

**Comment by niczero** [comment]
This is on my roadmap, but it's a fairly hefty task.  I don't think I can flag in the Makefile.PL that it is incompatible with Minion v6, so I might just need to add a big warning for now.  Hmm, I guess I could have a test that makes it immediately clear what the problem is.

**Comment by niczero** [comment]
The version currently on github supports all functionality of v6.03.  (The migration is proving easier than expected... so far.)
