### ISSUE TITLE
Invalid equality check in list_jobs

### ISSUE THREAD

**Issue by niczero** [niczero/minion-backend-storable#7]
Reported by @manuelm in amongst PR #2.

> e.g. modify https://github.com/kraih/minion/tree/master/examples/linkcheck to use Storable
> ./script/linkcheck minion job -e foo -a '[23, "bar"]'
> ./script/linkcheck minion job
> Use of uninitialized value in string eq at …/Minion/Backend/Storable.pm line 71.

**Comment by niczero** [comment]
@manuelm, I have a working unit test for this one too.
How about you create a new PR with _just_ the change to Storable.pm?  Then I can merge that into a release for tomorrow.

**Comment by manuelm** [comment]
~~Sure, if you want. Do you want me to remove this testcase https://github.com/niczero/minion-backend-storable/pull/2/commits/39254af50bb4704a140b4565d2b3e8818353c6d9#diff-f635e0684068ebb5429c39075efd225a as well?~~

nvm. mixed the two issues

**Comment by niczero** [comment]
This is fixed in v6.07 6ade8b3
